updated README, package.json and app.json.
2gather-app/togather2 pull request #9
Opened 2024-06-04 06:21 UTC by kachmashk

2024-06-04 06:21 UTC, kachmashk commented
* **#9** <a href="https://app.graphite.dev/github/pr/2gather-app/togather2/9?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @kachmashk and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-04 08:58 UTC, bionanek commented on app/Event/index.tsx
> +  const [state, setState] = useState(0)
this and useeffect below seems to be added by accident?

2024-06-04 08:59 UTC, bionanek commented on app/Event/index.tsx
> +      <Button
also shouldn't be pushed

2024-06-04 08:59 UTC, bionanek requested changes
remove dummy code and we're good to go

2024-06-05 07:33 UTC, bionanek approved these changes

2024-06-05 07:33 UTC, merged

2024-06-05 07:33 UTC, kachmashk commented
### Merge activity

* **Jun 5, 3:33 AM EDT**: @kachmashk merged this pull request with [Graphite](https://app.graphite.dev/github/pr/2gather-app/togather2/9).